services:
  - type: web
    name: next-js
    env: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DOMAIN_URL
        value: https://rupeetravel.com/
      - key: NEXT_PUBLIC_POSTHOG_KEY
        value: phc_2CUkJqHqAcHL3jh3w2bYDewU7CW0uakXoBTdU2ZzruH
      - key: NEXT_PUBLIC_POSTHOG_HOST
        value: https://us.i.posthog.com
